### ISSUE TITLE
Store flags encrypted with SHA256

### ISSUE THREAD

**Issue by ghost** [Goofygiraffe06/DailyCTFRobot#2]
In lines 75-84 of AdminCommands.py:
```python
challenge_data = {
          "master_id": interaction.user.id,
          "day": day,
          "desc": description,
          "answer": answer,
          "hints": hints,
          "writeup": writeup,
          "leaderboard": {},
          "start_time": int(datetime.datetime.utcnow().timestamp()),
      }
```
 instead of storing plaintext flag("answer"), store SHA256 encrypted version.
And in line 104 of GeneralCommands.py:
```python
if "answer" in challenge_data and challenge_data["answer"] == flag:
```
 compare extracted answer to encrypted inputted answer instead of plaintext.

**Comment by Goofygiraffe06** [comment]
We can't hash the flag as the bot is required to display the flag at the end of the challenge. Hashing would prevent us from doing this. If you have any alternative security measures please let me know. Thanks
